# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-13 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure', models.FloatField(default=-999.9)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('instrument', models.CharField(default=b'MPL3115A2', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(default=-999.9)),
                ('altitude', models.FloatField(default=float("nan"))),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('instrument', models.CharField(default=b'MPL3115A2', max_length=100)),
            ],
        ),
    ]
